// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vLtLFrKhRFL9hdlEFFk2H6lkTDt7xlc',
    appId: '1:1053319653484:web:4a297599d69729ba26d049',
    messagingSenderId: '1053319653484',
    projectId: 'roombooking-9577c',
    authDomain: 'roombooking-9577c.firebaseapp.com',
    storageBucket: 'roombooking-9577c.firebasestorage.app',
    measurementId: 'G-6RL1CY478Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlsCXl6d1X-4W78GLQ8jbCznY4_ZBMtgU',
    appId: '1:1053319653484:android:b1d614ebc5937f1726d049',
    messagingSenderId: '1053319653484',
    projectId: 'roombooking-9577c',
    storageBucket: 'roombooking-9577c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuibEhbmLbWQOFaMxAjJT04uLMAT8wQAY',
    appId: '1:1053319653484:ios:8ed767432ede747b26d049',
    messagingSenderId: '1053319653484',
    projectId: 'roombooking-9577c',
    storageBucket: 'roombooking-9577c.firebasestorage.app',
    iosBundleId: 'com.example.roombooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuibEhbmLbWQOFaMxAjJT04uLMAT8wQAY',
    appId: '1:1053319653484:ios:8ed767432ede747b26d049',
    messagingSenderId: '1053319653484',
    projectId: 'roombooking-9577c',
    storageBucket: 'roombooking-9577c.firebasestorage.app',
    iosBundleId: 'com.example.roombooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vLtLFrKhRFL9hdlEFFk2H6lkTDt7xlc',
    appId: '1:1053319653484:web:7f38d51398e92b0426d049',
    messagingSenderId: '1053319653484',
    projectId: 'roombooking-9577c',
    authDomain: 'roombooking-9577c.firebaseapp.com',
    storageBucket: 'roombooking-9577c.firebasestorage.app',
    measurementId: 'G-KG0V8VE74N',
  );
}
